apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "memegenerator.fullname" . }}
  labels:
{{ include "memegenerator.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/name: {{ include "memegenerator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}        
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: pre-delete-job
        image: "{{ .Values.deleteimage.repository }}:{{ .Values.deleteimage.tag }}"
        imagePullPolicy: {{ .Values.deleteimage.pullPolicy }}
        command: ["/bin/sh"]
        args: ["-c","/scripts/bringdown.sh"]
        env:
        - name: PROJECT
          value: family-connections-gke-test
        - name: INSTANCE_NAME
          value: memegen-db-24
        - name: INSTANCE_ZONE
          value: us-central1-c
        - name: BUCKET_NAME
          value: memegen-bucket-24
        - name: CLUSTER_NAME
          value: cluster-demo
